name: shimmerize_example
publish_to: none

description: Example app for shimmerize.

version: 0.0.1

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  shimmerize:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
